//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object ChangePassword {
            get {
                object obj = ResourceManager.GetObject("ChangePassword", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New School.
        /// </summary>
        internal static string SA_AddNewSchool {
            get {
                return ResourceManager.GetString("SA_AddNewSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary&amp;MiddleSchool.
        /// </summary>
        internal static string SA_ElementaryMiddleSchool {
            get {
                return ResourceManager.GetString("SA_ElementaryMiddleSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SA_Email {
            get {
                return ResourceManager.GetString("SA_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string SA_FirstName {
            get {
                return ResourceManager.GetString("SA_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighSchool.
        /// </summary>
        internal static string SA_HighSchool {
            get {
                return ResourceManager.GetString("SA_HighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string SA_LastName {
            get {
                return ResourceManager.GetString("SA_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preschool.
        /// </summary>
        internal static string SA_Preschool {
            get {
                return ResourceManager.GetString("SA_Preschool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name.
        /// </summary>
        internal static string SA_SchoolName {
            get {
                return ResourceManager.GetString("SA_SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SA_Select {
            get {
                return ResourceManager.GetString("SA_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select School Type.
        /// </summary>
        internal static string SA_SelectSchoolType {
            get {
                return ResourceManager.GetString("SA_SelectSchoolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical/Vocational School.
        /// </summary>
        internal static string SA_TechnicalVocationalSchool {
            get {
                return ResourceManager.GetString("SA_TechnicalVocationalSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SA_Title {
            get {
                return ResourceManager.GetString("SA_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object.
        /// </summary>
        internal static object Title {
            get {
                object obj = ResourceManager.GetObject("Title", resourceCulture);
                return ((object)(obj));
            }
        }
    }
}
