// <auto-generated />
namespace SchoolManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_ManagePayFee_and_ReceiptFeeType_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_ManagePayFee_and_ReceiptFeeType_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202208171039408_update_ManagePayFee_and_ReceiptFeeType_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
