// <auto-generated />
namespace SchoolManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddFieldTypeAndValues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFieldTypeAndValues));
        
        string IMigrationMetadata.Id
        {
            get { return "202206010508155_AddFieldTypeAndValues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
