// <auto-generated />
namespace SchoolManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_StudentTable_AddTransport_COL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_StudentTable_AddTransport_COL));
        
        string IMigrationMetadata.Id
        {
            get { return "202208190602132_update_StudentTable_AddTransport_COL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
