// <auto-generated />
namespace SchoolManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modifiy_SectionTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifiy_SectionTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202207091021118_modifiy_SectionTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
